name: server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Detect dependency-related changes
        id: deps_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            dependencies:
              - 'package.json'
              - 'package-lock.json'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: "npm"

      - name: Install Dependencies
        # Uncomment if you want to install only when deps change
        # if: steps.deps_changes.outputs.dependencies == 'true'
        run: npm install

      - name: Build the Project
        run: npm run build

      - name: Check if server is running and restart or start accordingly
        run: |
          if pm2 list | grep -q "server"; then
            echo "server is already running, restarting it..."
            pm2 restart server
          else
            echo "server is not running, starting it..."
            pm2 start npm --name "server" -- start
          fi

#
